# Generated by Django 5.1.3 on 2024-12-18 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tirador', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Entrenamiento', 'Entrenamiento'), ('Campeonato', 'Campeonato')], max_length=20)),
                ('campo', models.CharField(max_length=100)),
                ('modalidad', models.CharField(choices=[('Aire: Varmint Ligero', 'Aire: Varmint Ligero'), ('Aire: Varmint Pesado', 'Aire: Varmint Pesado'), ('BR-50: Sporter', 'BR-50: Sporter'), ('BR-50: Varmint Ligero', 'BR-50: Varmint Ligero'), ('BR-50: Varmint Pesado', 'BR-50: Varmint Pesado')], max_length=30)),
                ('arma', models.CharField(max_length=100)),
                ('marca_municion', models.CharField(max_length=100)),
                ('numero_disparos', models.PositiveIntegerField()),
                ('puntuacion', models.DecimalField(decimal_places=2, max_digits=6)),
                ('numero_dieces', models.PositiveIntegerField()),
                ('direccion_viento', models.CharField(choices=[('N', 'Norte'), ('NO', 'Noroeste'), ('O', 'Oeste'), ('SO', 'Suroeste'), ('S', 'Sur'), ('SE', 'Sureste'), ('E', 'Este'), ('NE', 'Noreste')], max_length=2)),
                ('velocidad_viento', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
